version: '3.8'

# Monitoring stack for Docker containers
# Usage: docker-compose -f docker-compose.monitoring.yml up

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: deer-pred-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - deer-pred-network

  grafana:
    image: grafana/grafana:latest
    container_name: deer-pred-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    networks:
      - deer-pred-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: deer-pred-cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - deer-pred-network

volumes:
  prometheus_data:
  grafana_data:

networks:
  deer-pred-network:
    external: true
