# Deduplication Script - Generated by Test Deduplicator
# Moves duplicate test files to archive

# Create archive directory
New-Item -ItemType Directory -Force -Path archive/tests/duplicates_$(Get-Date -Format 'yyyyMMdd')

# Archive test_multiple_locations.py
Move-Item 'test_multiple_locations.py' 'archive/tests/duplicates_$(Get-Date -Format "yyyyMMdd")/test_multiple_locations.py' -Force

# Archive test_camera_placement.py
Move-Item 'tests\unit\test_camera_placement.py' 'archive/tests/duplicates_$(Get-Date -Format "yyyyMMdd")/test_camera_placement.py' -Force
