name: Deer Prediction CI/CD

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-xdist pytest-timeout
      
      - name: Run Unit Tests
        run: |
          pytest tests/unit/ -v --tb=short --maxfail=5
        continue-on-error: false
      
      - name: Run Integration Tests (Fast)
        run: |
          pytest tests/integration/test_docker_health.py -v --tb=short -k "not timeout"
        continue-on-error: true
      
      - name: Run Critical GEE Tests
        env:
          EARTHENGINE_TOKEN: ${{ secrets.EARTHENGINE_TOKEN }}
        run: |
          pytest tests/unit/test_gee_data_validation.py -v --tb=short
        continue-on-error: true
      
      - name: Test Summary
        if: always()
        run: |
          echo "✅ CI/CD Pipeline Executed"
          echo "📊 Check test results above"

  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Backend Image
        run: |
          docker build -t deer-pred-backend:test .
      
      - name: Test Docker Image
        run: |
          docker run --rm deer-pred-backend:test python --version

  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Linters
        run: |
          pip install flake8 black isort
      
      - name: Check Code Formatting (Black)
        run: |
          black --check backend/ --diff
        continue-on-error: true
      
      - name: Check Import Sorting (isort)
        run: |
          isort --check-only backend/
        continue-on-error: true
      
      - name: Lint with Flake8
        run: |
          # Stop on critical errors
          flake8 backend/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # Warnings only for complexity
          flake8 backend/ --count --max-complexity=15 --max-line-length=120 --statistics
        continue-on-error: true

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Run Bandit Security Scan
        run: |
          pip install bandit
          bandit -r backend/ -ll
        continue-on-error: true
      
      - name: Check for Secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
        continue-on-error: true

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [test, docker-build]
    if: github.ref == 'refs/heads/develop'
    environment: staging
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Deploy to Staging
        run: |
          echo "🚀 Deploying to staging environment"
          echo "🔗 URL: https://staging.deer-prediction.app"
          # Add actual deployment commands here
      
      - name: Run Smoke Tests
        run: |
          echo "✅ Smoke tests passed"
          # Add smoke test commands here

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test, docker-build, security]
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    environment: production
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Deploy to Production
        run: |
          echo "🚀 Deploying to production"
          echo "⚠️  Manual approval required"
          # Add actual deployment commands here
      
      - name: Health Check
        run: |
          echo "✅ Production health check passed"
          # Add health check commands here
